[metadata]
name = klist2ccache
version = 0.2.0
description = Collect Windows Kerberos TGTs over SMB or WinRM and write MIT ccache files
url = https://github.com/jakeotte/klist2ccache
long_description = file: README.md
long_description_content_type = text/markdown

[options]
py_modules = klist2ccache
python_requires = >=3.8
install_requires =
    impacket>=0.12.0
    pywinrm>=0.5.0
    requests-ntlm2

[options.entry_points]
console_scripts =
    klist2ccache = klist2ccache:main
